### ISSUE TITLE
iOS 9 Support

### ISSUE THREAD

**Issue by DonTim** [iSECPartners/Introspy-iOS#38]
Does Introspy still work with iOS 9?

**Comment by radj** [comment]
I'm gonna have to say no, it does not. After installing it and rebooting the device, the device stayed stuck in boot mode.

Went through the process of restoring, rejailbreaking a device, and installing every dependency one by one, and rebooting after every dependency and I narrowed it down to one package having this problem: PreferenceLoader. I am not completely sure what this does for Introspy. Yet. Maybe Introspy can do without this and get settings/preferences somewhere else? I'm not sure.

**Comment by radj** [comment]
I'm gonna have to say no, it does not. After installing it and rebooting the device, the device stayed stuck in boot mode.

Went through the process of restoring, rejailbreaking a device, and installing every dependency one by one, and rebooting after every dependency. After I installed Introspy and rebooted via SSH, the device stayed stuck in boot (not a boot loop). Good thing I was able to recover by [putting device in Safe mode](http://www.iphonecaptain.com/enter-safe-mode-ios-device-iphone-ipod-ipad/) and removing the introspy package.

After removing introspy, rebooted again successfully. Reinstalled introspy, rebooted, stuck again. I think it is safe to say this is an introspy problem. Will look into it soon :)

**Comment by nabla-c0d3** [comment]
Regarding the reboot issues, this might help: https://github.com/nabla-c0d3/ssl-kill-switch2/issues/5

**Comment by radj** [comment]
@nabla-c0d3 I'll definitely look into it. Thanks for the lead!

**Comment by radj** [comment]
@nabla-c0d3 So from what I understood in that ticket, it was related to the page size. I updated my theos with the [pagesize fixes](https://github.com/rpetrich/theos/commit/2ca763fca78fee5629a6763b449ff28ce873109a) but the problem still occurs with Introspy. The [copy-only-when-needed approach](https://github.com/nabla-c0d3/ssl-kill-switch2/issues/5#issuecomment-149893123) is a good workaround but it only avoids the problem. Any other lead?

**Comment by DonTim** [comment]
I see ssl kill switch has been updated for iOS 9. Any chance someone can update introspy?

**Comment by nabla-c0d3** [comment]
@radj I ended up switching to kerb's theos (https://github.com/kirb/theos) for building the tweak and with the cydia substrate update, it fixed all the issues.

**Comment by DonTim** [comment]
@nabla-c0d3 Could you upload the compiled tweak? Thank you :+1:

**Comment by radj** [comment]
@nabla-c0d3 I started trying that repo now and ending up with more compile errors and warnings than before. Yikes. Might be a setup issue. Did you also just use  `git clone --recursive https://github.com/kirb/theos.git`? Or did you get your headers somewhere else?

**Comment by DonTim** [comment]
Any updates? @radj

**Comment by DonTim** [comment]
I managed to compile it for iOS 9 but it does not seem to log anything and no database gets created.

**Comment by yog3shsharma** [comment]
The same problem occurred for me too: "After installing it and rebooting the device, the device stayed stuck in boot mode" 

Is there any way workaround for it?

**Comment by radj** [comment]
@yog3shsharma Try the changes in this [pull request](https://github.com/iSECPartners/Introspy-iOS/pull/37/files):

**Comment by yog3shsharma** [comment]
Thanks for the prompt response @radj. I'll try and update here.

**Comment by radj** [comment]
It stops the bootloop but so far, Introspy hasn't worked for me yet. I haven't looked into that, too.

**Comment by Naville** [comment]
Gentleman.
I implemented my own version with improvements at https://github.com/Naville/WTFJH
Contains codes from this repo.
Hope that won't be a trouble

**Comment by radj** [comment]
So I think I've fixed the problem with iOS 9 thanks to @Naville's tips. I've made a [pull request](https://github.com/iSECPartners/Introspy-iOS/pull/37) that includes the change.

**Comment by jellylamp** [comment]
@radj I tried your changes but I still get stuck on the boot problem, is my setup correct?
* Made package with rpetrich THEOS
* Had to update theos with [http://stackoverflow.com/questions/21013325/dpkg-error-contains-ununderstood-data-member](this solution)
* Copied header files from mobilesubstrate as directed in step 5  [here](http://iphonedevwiki.net/index.php/Theos/Setup#On_Mac_OS_X_or_Linux)

I also tried using kirb/theos but ran into same `undeclared identifier HBLogError` errors that you mentioned.

**Comment by danylokostyshyn** [comment]
Have you tried adding a bundle filter for UIKit, like it was done [here](https://github.com/nabla-c0d3/ssl-kill-switch2/issues/5) in this [commit](https://github.com/nabla-c0d3/ssl-kill-switch2/commit/b8bd27ef23c622f5bb4b9237bb04bd1c9c7a3032) ?

**Comment by jellylamp** [comment]
@danylokostyshyn That fixed it! Thanks so much!
